# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/plain_processor/plain_processor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==plain_processor || ORIG_REF_NAME==plain_processor}]

# IP: bd/plain_processor/ip/plain_processor_processing_system7_0_0/plain_processor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==plain_processor_processing_system7_0_0 || ORIG_REF_NAME==plain_processor_processing_system7_0_0}]

# XDC: bd/plain_processor/ip/plain_processor_processing_system7_0_0/plain_processor_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==plain_processor_processing_system7_0_0 || ORIG_REF_NAME==plain_processor_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/plain_processor/plain_processor_ooc.xdc
